// Auto-generated by scripts/build-textbook-vocab-seed.js from
// scripts/output/taiwandiary-vocab.json. Do not edit by hand — re-run the scrape ->
// build pipeline (see KNOWLEDGE.md) if zh.taiwandiary.vn's content changes.
//
// Small hardcoded metadata for the "Sách Giáo Khoa" page (/textbook), the same
// "hardcode small enumerable metadata" convention as LEVEL_ORDER/TOPIC_ORDER — the
// page never needs a live query just to know what books/lessons exist.
export interface TextbookLesson {
  lessonId: number
  bookId: number
  lessonNo: number
  lessonName: string
}

export interface TextbookBook {
  bookId: number
  name: string
}

export const TEXTBOOK_BOOKS: TextbookBook[] = [
  { bookId: 1, name: "Đương Đại 1" },
  { bookId: 2, name: "Đương Đại 2" },
]

export const TEXTBOOK_LESSONS: TextbookLesson[] = [
  { lessonId: 1, bookId: 1, lessonNo: 1, lessonName: "Bài 1 - 歡迎你來臺灣！" },
  { lessonId: 2, bookId: 1, lessonNo: 2, lessonName: "Bài 2 - 我的家人" },
  { lessonId: 3, bookId: 1, lessonNo: 3, lessonName: "Bài 3 - 週末做什麼？" },
  { lessonId: 4, bookId: 1, lessonNo: 4, lessonName: "Bài 4 - 請問一共多少錢？" },
  { lessonId: 5, bookId: 1, lessonNo: 5, lessonName: "Bài 5 - 牛肉麵真好吃" },
  { lessonId: 6, bookId: 1, lessonNo: 6, lessonName: "Bài 6 - 他們學校在山上" },
  { lessonId: 7, bookId: 1, lessonNo: 7, lessonName: "Bài 7 - 早上九點去KTV" },
  { lessonId: 8, bookId: 1, lessonNo: 8, lessonName: "Bài 8 - 坐火車去臺南" },
  { lessonId: 9, bookId: 1, lessonNo: 9, lessonName: "Bài 9 - 放假去哪裡玩？" },
  { lessonId: 10, bookId: 1, lessonNo: 10, lessonName: "Bài 10 - 臺灣的水果很好吃" },
  { lessonId: 11, bookId: 1, lessonNo: 11, lessonName: "Bài 11 - 我要租房子" },
  { lessonId: 12, bookId: 1, lessonNo: 12, lessonName: "Bài 12 - 你計畫在臺灣學多久的中文？" },
  { lessonId: 13, bookId: 1, lessonNo: 13, lessonName: "Bài 13 - 生日快樂" },
  { lessonId: 14, bookId: 1, lessonNo: 14, lessonName: "Bài 14 - 天氣這麼冷！" },
  { lessonId: 15, bookId: 1, lessonNo: 15, lessonName: "Bài 15 - 我很不舒服" },
  { lessonId: 16, bookId: 2, lessonNo: 1, lessonName: "Bài 1 - 請問，到師大怎麼走？" },
  { lessonId: 17, bookId: 2, lessonNo: 2, lessonName: "Bài 2 - 還是坐捷運吧！" },
  { lessonId: 18, bookId: 2, lessonNo: 3, lessonName: "Bài 3 - 你的中文進步了！" },
  { lessonId: 19, bookId: 2, lessonNo: 4, lessonName: "Bài 4 - 我打工，我教法文" },
  { lessonId: 20, bookId: 2, lessonNo: 5, lessonName: "Bài 5 - 吃喜酒" },
  { lessonId: 21, bookId: 2, lessonNo: 6, lessonName: "Bài 6 - 我打算搬到學校附近" },
  { lessonId: 22, bookId: 2, lessonNo: 7, lessonName: "Bài 7 - 垃圾車來了！" },
  { lessonId: 23, bookId: 2, lessonNo: 8, lessonName: "Bài 8 - 學功夫" },
  { lessonId: 24, bookId: 2, lessonNo: 9, lessonName: "Bài 9 - 那個城市好漂亮" },
  { lessonId: 25, bookId: 2, lessonNo: 10, lessonName: "Bài 10 - 歡迎到我家來包餃子" },
  { lessonId: 26, bookId: 2, lessonNo: 11, lessonName: "Bài 11 - 台灣好玩的地方真多" },
  { lessonId: 27, bookId: 2, lessonNo: 12, lessonName: "Bài 12 - 怎麼吃才健康？" },
  { lessonId: 28, bookId: 2, lessonNo: 13, lessonName: "Bài 13 - 我的手機掉了" },
  { lessonId: 29, bookId: 2, lessonNo: 14, lessonName: "Bài 14 - 我要開始找工作了" },
  { lessonId: 30, bookId: 2, lessonNo: 15, lessonName: "Bài 15 - 過春節" },
]

export function lessonsForBook(bookId: number): TextbookLesson[] {
  return TEXTBOOK_LESSONS.filter((l) => l.bookId === bookId).sort((a, b) => a.lessonNo - b.lessonNo)
}
